version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: postech-documentdb-ponto-eletronico
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Mudar1234
      MONGO_INITDB_DATABASE: ponto-eletronico
    command: >
      mongo admin -u admin -p Mudar1234 --eval "
      db = db.getSiblingDB('clientes');
      db.createUser({
        user: 'cliente_user',
        pwd: 'cliente_password',
        roles: [{ role: 'read', db: 'ponto-eletronico' }]
      });"

  mysql:
    image: mysql:latest
    container_name: postech-rds-hackaton-funcionarios
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: funcionarios
    ports:
      - "3306:3306"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: postech-hackaton-keycloak
    restart: on-failure
    command:
      - start-dev 
      - --import-realm
    volumes:
      - ./infra:/config/
    environment:
      - KEYCLOAK_USER=user
      - KEYCLOAK_PASSWORD=Mudar1234
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Mudar1234
      - DB_VENDOR=MYSQL
      - DB_ADDR=mysql
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=mysecretpassword
    ports:
      - "8083:8080"
    depends_on:
      - mysql

  # postech-hackaton-ponto-eletronico:
  #   depends_on:
  #     - mongodb
  #   image: danielmaria/postech-hackaton/postech-ponto-eletronico:latest
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_USERNAME: admin
  #     SPRING_DATASOURCE_PASSWORD: Mudar1234
  #     LOGGING_LEVEL_ROOT: INFO

  # postech-hackaton-relatorios:
  #   depends_on:
  #     - mongodb
  #   image: danielmaria/postech-hackaton/postech-clientes:latest
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mongo://mongodb:27017/ponto-eletronico #Talvez mudar para o nome do container 
  #     SPRING_DATASOURCE_USERNAME: cliente_user 
  #     SPRING_DATASOURCE_PASSWORD: cliente_password
  #     LOGGING_LEVEL_ROOT: INFO

  # postech-hackaton-funcionarios:
  #   depends_on:
  #     - mysql
  #   image: danielmaria/postech-hackaton/postech-funcionarios:latest
  #   ports:
  #     - "8082:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/funcionarios #Talvez mudar para o nome do container
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: mysecretpassword
  #     LOGGING_LEVEL_ROOT: INFO
